# Site Settings
title: "Matthew Kowal"
description: "AI Interpretability Researcher"
url: https://mkowal2.github.io
baseurl: ""
locale: "en-US"

# Author
author:
  name: "Matthew Kowal"
  email: "matt2kowal@gmail.com"
  bio: "AI Interpretability Researcher"
  avatar: "Matt3.jpg"
  github: "MKowal2"
  twitter: "MatthewKowal9"
  linkedin: "mkowal2"
  googlescholar: "https://scholar.google.com/citations?user=FCg8QxUAAAAJ&hl=en"

# Build
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
excerpt_separator: "\n\n"

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Collections
collections:
  publications:
    output: false
  hobbies:
    output: true
    permalink: /hobbies/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: default

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Reading Files
include:
  - _pages
  - files
exclude:
  - .sass-cache
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - CHANGELOG.md
  - CONTRIBUTING.md
keep_files:
  - .git

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
